INSERT INTO aip_posts(user_id, title, link, by, content, post_type, date_created)
VALUES
('1','What Is The Plan Today To Reduce Inflammation?','https://www.paddisonprogram.com/blog/','','','podcast',now() - '1 days'::INTERVAL),
('2','Some Uplifting Event','https://www.google.com/','','Get inspired. Get uplifted. Connect','event',now() - '1 days'::INTERVAL),
('1','Gluten free garlic, rosemary crackers','https://www.amymyersmd.com/recipe/gluten-free-garlic-rosemary-crackers/','Amy Myers','','recipe',now() - '1 days'::INTERVAL),
('1','Enzymes keep us beautiful','https://mysolluna.com/blog/2020/03/07/enzymes-keep-us-beautiful/','Kimberly Snyder','','lifestyle',now() - '1 days'::INTERVAL),
('2','New Year’s True Beauty Rituals – Trade Resolutions for Rituals!','','Kimberly Snyder','','lifestyle',now() - '1 days'::INTERVAL),
('2','The Autoimmune Solution','','Amy Myers','Considered the definitive guide to reversing autoimmunity, The Autoimmune Solution lays out a revolutionary, step-by-step approach that restores the body to its natural healthy state in 30 days by eliminating toxic foods, introducing restorative ingredients, and identifying environmental toxins.','book',now() - '1 days'::INTERVAL),
('3','Gluten free garlic, rosemary crackers','https://www.amymyersmd.com/recipe/gluten-free-garlic-rosemary-crackers/','Amy Myers','','recipe',now() - '1 days'::INTERVAL),
('1','Enzymes keep us beautiful','https://mysolluna.com/blog/2020/03/07/enzymes-keep-us-beautiful/','Kimberly Snyder','','lifestyle',now() - '1 days'::INTERVAL),
('4','New Year’s True Beauty Rituals – Trade Resolutions for Rituals!','','Kimberly Snyder','','lifestyle',now() - '1 days'::INTERVAL),
('2','The Autoimmune Solution','','Amy Myers','Considered the definitive guide to reversing autoimmunity, The Autoimmune Solution lays out a revolutionary, step-by-step approach that restores the body to its natural healthy state in 30 days by eliminating toxic foods, introducing restorative ingredients, and identifying environmental toxins.','book',now() - '1 days'::INTERVAL),
('5','Glowing Green Smoothie','','Kimberly Snyder','','book',now() - '1 days'::INTERVAL),
('2','Some Uplifting Event','https://www.google.com/','','Get inspired. Get uplifted. Connect','event',now() - '1 days'::INTERVAL),
('2','Paleo Principles','','Sarah Ballantyne','From the New York Times bestselling author of The Paleo Approach and The Healing Kitchen comes the most comprehensive resource to date for those seeking a scientifically founded nutritional approach to optimal health.','book',now() - '1 days'::INTERVAL),
('3','','','','In order to love who you are, you cannot hate the experiences that shaped you','podcast',now() - '1 days'::INTERVAL),
('1','','','','If you are walking a path of low expectations, the next thing you find will support those low expectations.  -Deepak Chopra','book',now() - '1 days'::INTERVAL),
('1','Three Little Birds','https://youtu.be/zaGUr6wzyT8','','Bob Marley','event',now() - '1 days'::INTERVAL),
('2','It''s a Great Day to Be Alive','https://youtu.be/aexnDmumVf8','Darrell Scott','','event',now() - '1 days'::INTERVAL),
('1','Reinventing the Body, Resurrecting the Soul','','Deepak Chopra','Transformation can''t stop with the body, however; it must involve the soul. The soul–seemingly invisible, aloof, and apart from the material world–actually creates the body. Only by going to the level of the soul will you access your full potential, bringing more intelligence, creativity, and awareness into every aspect of your life.','book',now() - '1 days'::INTERVAL),
('3','','','','Remember to take some time alone with yourself and tune into what feels true beyond the voice of ego and external forces','podcast',now() - '1 days'::INTERVAL),
('3','What Is The Plan Today To Reduce Inflammation?','https://www.paddisonprogram.com/blog/','','','podcast',now() - '1 days'::INTERVAL),
('2','Some Uplifting Event','https://www.google.com/','','Get inspired. Get uplifted. Connect','event',now() - '1 days'::INTERVAL),
('1','Gluten free garlic, rosemary crackers','https://www.amymyersmd.com/recipe/gluten-free-garlic-rosemary-crackers/','Amy Myers','','recipe',now() - '1 days'::INTERVAL),
('1','Enzymes keep us beautiful','https://mysolluna.com/blog/2020/03/07/enzymes-keep-us-beautiful/','Kimberly Snyder','','lifestyle',now() - '1 days'::INTERVAL),
('2','New Year’s True Beauty Rituals – Trade Resolutions for Rituals!','','Kimberly Snyder','','lifestyle',now() - '1 days'::INTERVAL),
('2','The Autoimmune Solution','','Amy Myers','Considered the definitive guide to reversing autoimmunity, The Autoimmune Solution lays out a revolutionary, step-by-step approach that restores the body to its natural healthy state in 30 days by eliminating toxic foods, introducing restorative ingredients, and identifying environmental toxins.','book',now() - '1 days'::INTERVAL),
('3','Gluten free garlic, rosemary crackers','https://www.amymyersmd.com/recipe/gluten-free-garlic-rosemary-crackers/','Amy Myers','','recipe',now() - '1 days'::INTERVAL),
('1','Enzymes keep us beautiful','https://mysolluna.com/blog/2020/03/07/enzymes-keep-us-beautiful/','Kimberly Snyder','','lifestyle',now() - '1 days'::INTERVAL),
('1','New Year’s True Beauty Rituals – Trade Resolutions for Rituals!','','Kimberly Snyder','','lifestyle',now() - '1 days'::INTERVAL),
('2','The Autoimmune Solution','','Amy Myers','Considered the definitive guide to reversing autoimmunity, The Autoimmune Solution lays out a revolutionary, step-by-step approach that restores the body to its natural healthy state in 30 days by eliminating toxic foods, introducing restorative ingredients, and identifying environmental toxins.','book',now() - '1 days'::INTERVAL),
('5','Glowing Green Smoothie','','Kimberly Snyder','','book',now() - '1 days'::INTERVAL),
('3','Reinventing the Body, Resurrecting the Soul','','Deepak Chopra','Transformation can''t stop with the body, however; it must involve the soul. The soul–seemingly invisible, aloof, and apart from the material world–actually creates the body. Only by going to the level of the soul will you access your full potential, bringing more intelligence, creativity, and awareness into every aspect of your life.','book',now() - '1 days'::INTERVAL),
('4','','','','My inner growth propelled me to by my own I-to be an authentic woman who was contained in herself, who chose and determined and handled her life from her own genuine spiritual center  -Sue Monk Kidd','event',now() - '1 days'::INTERVAL)
